### ISSUE TITLE
How to regenerate?

### ISSUE THREAD

**Issue by Ploppz** [barskern/sbanken-rs#1]
It seems like some structs are outdated and I think regeneration is needed.
What is the command to regenerate the code?
Maybe it can be included in the repo as a shell file?

**Comment by Ploppz** [comment]
I tried with this
```sh
openapi-generator generate -i https://publicapi.sbanken.no/openapi/proxy/bff-apibeta/swagger/v2/swagger.json -g rust
```
Which seems to work well. I realized that the code is not outdated however, but the OpenAPI spec seems wrong. Made an issue in sbanken.

**Comment by barskern** [comment]
Ah, I didn't know that the API spec has been updated, I will see if I can update this in the near future too. It seems as though there has been a fundemental change to a single swagger file which should make the setup easier. Anyways, I have this highly personalized repository which does the generating for me using some Makefiles. For reference you could find it here: https://gitlab.com/barskern/openapi-generators
